apiVersion: v2
name: stalwart
description: Helm chart for Stalwart Mail Server (0.16+ datastore config model)
type: application
version: 0.4.2
appVersion: "0.16.25"
kubeVersion: ">= 1.26.0"
home: https://github.com/itsh-cloud/stalwart-helm
sources:
  - https://github.com/itsh-cloud/stalwart-helm
  - https://github.com/stalwartlabs/stalwart
maintainers:
  - name: Giovanni Harting
    url: https://github.com/an0nfunc
keywords:
  - stalwart
  - mail-server
  - smtp
  - imap
  - jmap
  - email
